# permissions for end users to edit aorjoapainkillers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: aorjoapainkiller-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd
    app.kubernetes.io/part-of: crd
    app.kubernetes.io/managed-by: kustomize
  name: aorjoapainkiller-editor-role
rules:
- apiGroups:
  - example.aor.dev
  resources:
  - aorjoapainkillers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.aor.dev
  resources:
  - aorjoapainkillers/status
  verbs:
  - get
