---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - example.aor.dev
  resources:
  - aorjoapainkillers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.aor.dev
  resources:
  - aorjoapainkillers/finalizers
  verbs:
  - update
- apiGroups:
  - example.aor.dev
  resources:
  - aorjoapainkillers/status
  verbs:
  - get
  - patch
  - update
